---
- name: Controller Demo
  hosts: all
  sources:
    - ansible.eda.range:
        limit: 5
  rules:
    - name: Label Rule
      condition: event.i == 1
      action:
        run_job_template:
          name: Demo Job Template
          organization: Default
          labels:
            - "{{ user_label | default('User defined label') }}"
...
